let eng = {
   topSubtitle: "The Portfolio of Alex Lin",
    nav_1: "ABOUT ME",
    nav_2: "My Skill",
    nav_3: "Reviews",
    nav_4: "My knowledge",
    nav_5: "Contact me",
    menu: "menu",
  about__title: "About me",
  about__text_one: "Hey! I am 23 years old and I am a web developer striving to keep abreast of new developments on the web! I am in constant development and training, take courses, attend conferences. I create functional interactive websites responsive on all platforms and devices." ,
  About__text: "The only way to do great work is to love what you do. And damn it, that's exactly what I love!",
meskill__title: "Skill Set",
myskill__subtitle: "Fast, Better, More Modern",
knowledge__title: "I study",
reviews__button:"Add a review",
review__link: "view work",
contacts__subtitle: "Contact me",
form__name: "Name",
form__phone: "Phone",
form__mesege: "Messege",
form__date: "Indicate when the work was done",
form__link: "link",
form__leave:"Leave a Review",
knowledge_block: "No one is going to hand me success. I must go out & get it myself. That’s why I’m here. To dominate. To conquer. Both the world, and myself.",
work_title: "My work",
work_text: "To write correct code, we first write incorrect code and then refactor it.",
work_link: " The rest of the work can be found on GitHab",
send_active_1: "Your message has been successfully sent!",
send_active_2: "I will contact you shortly",
page_mistake_1: "An error has occurred!",
page_mistake_2: "Please try again later",
work_buttons: "View work",
revier_active_1: "Your review will be added after verification",
revier_active_1: "Thank! Your feedback is very important to me.",
css_2: "Crossbrowser code",
css_3: "File structure according to Bam",
js_2: "Commented code",
js_4: "Custom js code",
sass_1: "Simplified syntax",
sass_2: "Accelerated styling",
sass_3: "Nesting",
sass_4: "More flexible code",
bem_1: "Nested file structure",
bem_2: "Uniform standards",
bem_3: "Increased productivity",
react_1: "High level of flexibility",
react_2: "maximum responsiveness",
react_3: "Two-way data binding",
webpack_1: "Dynamic file upload",
webpack_2: "Dynamic code update",
webpack_3: "Generating multiple files",
html_1: "Sematic code",
html_2: "Bam writing",
html_3: "high stability",
figma_1: "Convenient built-in developer mode",
figma_2: "Co-editing",
figma_3: "Multitasking",
loaded3: "My main activity is Frontend development. My goal is responsive, cross-browser, readable code. Perhaps I am exactly who you are looking for!",
}

let rus = {
  topSubtitle: "Портфолио Алексея Фомина",
 nav_1: "Обо мне",
  nav_2: "Мой навыки",
  nav_3: "Отзывы",
  nav_4: "Мой работы",
  nav_5: "Связь со мной",
   menu: "Меню",
about__title: "Обо мне",
about__text_one: "Привет! Мне 23 года и я веб разработчик стремящийся постоянно быть в курсе новых событий в вебе! Нахожусь в постоянном развитий и обучений , прохожу курсы, посещаю конференций. Создаю функциональные интерактивные веб сайты адаптивные на всех платформах и устройствах.",
About__text: "Единственный способ делать отличную работу - любить то, что делаешь. И черт возьми это имменно то что я люблю!",
meskill__title: "С этим я работаю",
myskill__subtitle: "Быстрые.Лучше.Cовременнее",
knowledge__title: "Я изучаю:",
reviews__button:"Добавить отзыв",
review__link: "Посмотреть работу",
contacts__subtitle: "Связаться со мной",
form__name: "Ваше имя",
form__phone: "Ваш номер телефона",
form__mesege: "Сообщение",
form__date: "Укажите когда была выполнена работа",
form__link: "Ссылка",
form__leave:"Оставить отзыв",
knowledge_block: "Никто не предоставит мне успех. Я должен пойти и добиться его сам. Вот почему я здесь. Чтобы доминировать и одержать победу. Над этим миром и над собой" , 
work_title: "Мой работы",
work_text: "Чтобы написать чистый код, мы сначала пишем грязный код, а затем рефакторим его.",
work_link: "С остальными работами можно ознакомится на GitHab",
send_active_1: "Ваще сообщение успешно отправлена!",
send_active_2: "В скорое время я с вами свяжусь",
page_mistake_1: "Произошла ошибка!",
page_mistake_2: "Повторите попытку позже",
work_buttons: "Посмотреть работу",
revier_active_1: "Ваш отзыв будет добавлен после проверки",
revier_active_1: "Спасибо! Ваше мнение очень важно для меня!",
css_2: "Кроссбраузерный код",
css_3: "Фаиловая структура по Бэм",
js_2: "Комментируемый код",
js_4: "Индивидуальный код js",
sass_1: "Упрошенный синтаксис",
sass_2: "Ускоренная стилизация",
sass_3: "Вложенность",
sass_4: "Более гибкий код",
bem_1: "файловая структура Nested",
bem_2: "Единные стандарты",
bem_3: "Увиличивание производительности",
react_1: "Высокий уровень гибкости",
react_2: "максимальная отзывчивость",
react_3: "Двусторонняя привязка данных",
webpack_1: "Динамическая подгрузка файлов",
webpack_2: "Динамическое обновление кода",
webpack_3: "Генерация нескольких файлов",
html_1: "Сематический код",
html_2: "Написание по бэм",
html_3: "высокая стабильность",
figma_1: "Удобный встроенный режим для разработчика",
figma_2: "Совместное редактирование",
figma_3: "Многозадачность",
loaded3: "Основная моя деятельность Frontend разработка. Моя цель - адаптивный, кроссбраузерный, читабельный код. Возможно я именно тот кого вы ищите!",
};

changeLagnuage();

const spanDelete = document.querySelector(".lader__text");
const loadedOpen = document.querySelector(".lader__text_rus");
const lungNow = document.querySelector(".header__tongue-button")
lungNow.addEventListener("click", () => {
    loadedOpen.style.display = "block";
    spanDelete.style.display = "none";
   
})

 

function changeLagnuage(){
  let language = lang.checked ? rus : eng;
  document.querySelectorAll('[text]').forEach(el => {
    el.innerHTML = language[el.getAttribute('text')];

  })
}
